# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-07 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_recieveproductaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='recieveproductaddress',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
