# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-07 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_driver'),
        ('program', '0006_auto_20180307_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportWithOrderTransection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Driver')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.Order')),
            ],
        ),
    ]
