# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-09 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0008_auto_20180308_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='transportwithordertransection',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='trans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.TransportWithOrderTransection'),
        ),
    ]
