# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-09 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0009_auto_20180309_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertracking',
            name='trans',
        ),
        migrations.AddField(
            model_name='transportwithordertransection',
            name='order_tracking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='program.OrderTracking'),
        ),
    ]
