# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-05 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_pk',
            field=models.IntegerField(default=0),
        ),
    ]
